name: singtaxi
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  provider: ^3.1.0
  flutter_spinkit: "4.1.2"
  firebase_database: ^3.1.3
  rxdart: any
  google_maps_flutter: 0.5.25+1
  geoflutterfire: ^2.0.2
  location: ^2.3.5
  fluttertoast: ^3.1.3
  flutter_datetime_picker: ^1.2.5
  datetime_picker_formfield: any
  google_map_polyline: 0.2.0+1
  simple_animations: 1.3.11
  http: 0.12.0+4
  cached_network_image: 2.0.0





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.5
  firebase_storage: 3.1.3
  font_awesome_flutter: ^8.7.0
  image_picker: ^0.5.3+1
  flip_card: 0.4.4
  multiple_select: ^0.1.22
  giffy_dialog: 1.7.0
  rate_my_app: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - android/assets/LoginPage.jpg
   - android/assets/HomePage.jpg
   - android/assets/WelcomePage.jpg
   - android/assets/google-icon.png
   - android/assets/PHOTO-2020-02-12-17-33-01.png
   - android/assets/merlion.jpeg
   - android/assets/cony.jpg
   - android/assets/UserPreference.jpg
   - android/assets/mastercard.png
   - android/assets/visacard.png
   - android/assets/taxi.jpg
   - android/assets/friend.jpg
   - android/assets/Huang.jpg
   - android/assets/Lin.jpg
   - android/assets/Luo.jpg
   - android/assets/Ong.jpg
   - android/assets/destination_map_marker.png
   - android/assets/data.json
   - android/assets/data2.json
   - android/assets/data3.json
   - android/assets/data4.json
   - android/assets/cryFace.png
   - android/assets/logo.jpg
   - android/assets/futuretaxi.gif
   #- images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
